### ISSUE TITLE
Create SDoH intermediate model & guide notebook

### ISSUE THREAD

**Issue by kzollove** [TuftsCTSI/TRDW-Guides#3]
Compile a notebook of the available SDoH variables from EHR and other source

See the work done to collect this information in one place:

https://github.com/TuftsCTSI/TRDW-ETL/issues/135

**Comment by clarkevans** [comment]
Reviewers when this is completed would be ... @wiharvey @AEW0330

**Comment by kzollove** [comment]
More tobacco/nicotine records in Soarian diagnoses:
```
SELECT DISTINCT Code, CodeDescription FROM mir_sc_diagnosis
Where CodeDescription ILIKE '%nicotine%' limit 100
```
